name: internet_calendar
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/shaakunuigurumi/internet_calendar.dart

environment:
  sdk: '>3.0.0 <=4.0.0'

# Add regular dependencies here.
dependencies:
  meta: ^1.16.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0
